-- Migration: Insert MIRABAL CAFE products from Supabase
-- Generated: 152 products
-- Target branch: MIRABAL CAFE (MRABAL CAFE)

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

BEGIN;

INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'A pair of Samosa and French Fries', 15000, 'All Day Dining', 'https://i.ibb.co/YFfTtZ3K/7565bfb15432.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Almond Croissant', 9000, 'Pastries', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Americano', 8000, 'Expresso Bar', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Banana Peanut Smoothie', 14000, 'Smoothies', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'BBQ Chicken Pizza', 35000, 'Pizzas', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Beef Lily Sandwiches', 25000, 'Sandwiches', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Beef Luwombo', 28000, 'Local', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Beef Luwombo', 28000, 'Local', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Beef Pie', 12000, 'Pies & Samosas', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Beef Samosa', 5000, 'Pies & Samosas', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Beef Stew & Rice', 20000, 'Mains', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Beef Stew & Rice', 20000, 'Mains', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Beef Tenderloin Steak', 45000, 'Main Course', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Belligian Waffle', 20000, 'Breakfast', 'https://i.ibb.co/FkbQHnWP/7ed041ecfe55.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Black Tea', 5000, 'Drinks', 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Blueberry Muffin', 7000, 'Pastries', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Butter Milk PanCakes', 10000, 'Breakfast', 'https://i.ibb.co/SDDhcPPv/f32eb5554707.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Cappuccino', 12000, 'Cappuccinos', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Caramel Booster', 14000, 'Booster Coffees', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Caramel Latte', 14000, 'Flavoured Lattes', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Carrot Cake Slice', 10000, 'Cake Slices', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Chamomile Tea', 7000, 'Teas', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Chapati Pair', 5000, 'All Day Dining', 'https://i.ibb.co/8nxt1NKN/25db2f0e3b73.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Cheese Baguette', 12000, 'Baguettes', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Cheesecake Slice', 12000, 'Cake Slices', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Chefs Daily Specialty', 20000, 'All Day Dining', 'https://i.ibb.co/s9tL8NHm/3e4e4650b785.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Chicken Pie', 12000, 'Pies & Samosas', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Chocolate Brownie', 9000, 'Desserts', '', FALSE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Chocolate Cake Slice', 15000, 'Desserts', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Chocolate Cake Slice', 10000, 'Cake Slices', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Chocolate Milkshake', 12000, 'Milkshakes', '', FALSE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Choice of Freshly Squeezes Juices', 12000, 'Breakfast', 'https://i.ibb.co/d49Y2Z2n/5fad37f57c27.png', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Cinnamon Danish', 8000, 'Pastries', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Classic Ceasar Salads', 25000, 'All Day Dining', 'https://i.ibb.co/vvqmrpWs/71a608456a15.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Classic Club Sandwichs', 30000, 'Sandwiches', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Classic Lemonade', 8000, 'Lemonades', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Classic Mojito', 14000, 'Mojitos', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Clear Chicken cream of Mushroom Soup', 15000, 'All Day Dining', 'https://i.ibb.co/20w3jsJX/2a1a5bfb8d55.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Clear Chicken cream of Pumpkin Soup', 15000, 'All Day Dining', 'https://i.ibb.co/vCT3PMv3/98e2866172f5.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Clear Chicken Cream of Tomato Soup ', 15000, 'All Day Dining', 'https://i.ibb.co/fYrN3wbd/518ab9f6ee68.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Coca-Cola 500ml', 4000, 'Drinks', 'https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=600&q=80', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Coca-Cola 500ml', 4000, 'Drinks', 'https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=600&q=80', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Continental BreakFast', 30000, 'Breakfast', 'https://i.ibb.co/6csRTLtc/f234099271b8.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Cortado', 10000, 'Expresso Bar', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Creme Brulee', 14000, 'Desserts', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Croissant', 7000, 'Pastries', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Custom Birthday Cake', 100000, 'Whole Cakes', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Design Your Own Sandwiches', 20000, 'Sandwiches', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Double Espresso', 8000, 'Expresso Bar', '', FALSE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Dry Cappuccino', 12000, 'Cappuccinos', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'English Breakfast Tea', 6000, 'Teas', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Espresso', 5000, 'Expresso Bar', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Extra Burger Toppings Bacon', 10000, 'Burgers', 'https://i.ibb.co/0jP1vqG6/f3b7b9db0190.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Extra Burger Toppings Fried Eggs', 10000, 'Burgers', 'https://i.ibb.co/VWCv7cQD/1cc414b96180.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Extra Burger Toppings Onion Rings', 10000, 'Burgers', 'https://i.ibb.co/Cs4D97V3/c49429bc8805.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Fanta Orange 500ml', 4000, 'Drinks', 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=600&q=80', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Fettuccine Alfredo', 22000, 'Pastas', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Flame Grilled Chicken Burger', 25000, 'Burgers', 'https://i.ibb.co/mFcmV5SS/d3f69eeb6df3.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'French Fries Plain', 10000, 'All Day Dining', 'https://i.ibb.co/KjXw25J5/05d754aa7f6e.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Fresh Garden Salad', 15000, 'Appetizers', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Fresh Garden Salad', 15000, 'Appetizers', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Fresh Mango Juice', 9000, 'Fresh Juice', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Fresh Orange Juice', 9000, 'Fresh Juice', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Fresh Passion Fruit Juice', 9000, 'Fresh Juice', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Fresh Pineapple Juice', 9000, 'Fresh Juice', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Fresh Watermelon Juice', 9000, 'Fresh Juice', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Fruit Salad', 10000, 'Desserts', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Garlic Herb Baguette', 10000, 'Baguettes', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Ginger Lemonade', 9000, 'Lemonades', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Green Detox Smoothie', 13000, 'Smoothies', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Green Tea', 7000, 'Teas', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Grilled Chicken & Chips', 22000, 'Mains', 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Grilled Chicken & Chips', 22000, 'Mains', 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Grilled Chicken Breast', 32000, 'Main Course', '', FALSE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Hazelnut Booster', 14000, 'Booster Coffees', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Hazelnut Latte', 14000, 'Flavoured Lattes', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Ice Cream Scoop', 5000, 'Desserts', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Ice Cream Sundae', 12000, 'Desserts', 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=600&q=80', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Ice Cream Sundae', 12000, 'Desserts', 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=600&q=80', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Iced Cappuccino', 14000, 'Cappuccinos', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'International Breakfast', 35000, 'Breakfast', 'https://i.ibb.co/pvzVwfwh/73a7edca182f.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Krown Signature Burger', 25000, 'Burgers', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Krown Signature Burger', 25000, 'Burgers', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Lasagna', 25000, 'Pastas', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Lemon Drizzle Slice', 10000, 'Cake Slices', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Macchiato', 9000, 'Expresso Bar', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Maisha (Healthy BreakFast)', 30000, 'Breakfast', 'https://i.ibb.co/DfBNB8W2/1be018c97139.png', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Mango Colada', 15000, 'Coladas', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Mango Milkshake', 12000, 'Milkshakes', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Mango Mojito', 15000, 'Mojitos', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Margherita Pizza', 28000, 'Pizzas', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Masala Chai', 8000, 'Teas', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Matooke & Groundnut Stew', 18000, 'Local', 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Matooke & Groundnut Stew', 18000, 'Local', 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Mineral Water 500ml', 3000, 'Drinks', 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?auto=format&fit=crop&w=600&q=80', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Mineral Water 500ml', 3000, 'Drinks', 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?auto=format&fit=crop&w=600&q=80', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Mint Lemonade', 9000, 'Lemonades', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Mirabal Special Pizza', 38000, 'Pizzas', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Mixed Berry Smoothie', 13000, 'Smoothies', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Mocha Booster', 14000, 'Booster Coffees', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Mocha Latte', 14000, 'Flavoured Lattes', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Multigrain Loaf', 18000, 'Bread Loaves', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Olive Sourdough', 22000, 'Sour Dough Breads', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Omellete And Specials', 30000, 'Mains', 'https://i.ibb.co/sdVvLbz2/670c802d6bce.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Pain au Chocolat', 8000, 'Pastries', '', FALSE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Pan Fried Fillet of Tilapia', 30000, 'Main Course', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Passion Fruit Mojito', 15000, 'Mojitos', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Penne Arrabbiata', 20000, 'Pastas', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Peppermint Tea', 7000, 'Teas', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Pepperoni Pizza', 30000, 'Pizzas', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Pepperoni Pizza', 30000, 'Pizzas', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Pepperoni Pizza', 32000, 'Pizzas', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Pina Colada', 15000, 'Coladas', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Plain Baguette', 8000, 'Baguettes', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Plain Sourdough Loaf', 18000, 'Sour Dough Breads', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Pork Tenderloin', 38000, 'Main Course', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Posho & Beans', 12000, 'Local', 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Prime Beef Burger', 25000, 'Burgers', 'https://i.ibb.co/JRG77Rym/945b1e0b8ec4.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Red Velvet Slice', 12000, 'Cake Slices', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Rosemary Sourdough', 20000, 'Sour Dough Breads', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Salads', 20000, 'All Day Dining', 'https://i.ibb.co/B2kfcH4R/091d805b5c3a.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Spaghetti Bolognese', 22000, 'Pastas', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Spaghetti Carbonara', 24000, 'Pastas', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Spring Rolls (6)', 10000, 'Appetizers', 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Strawberry Colada', 15000, 'Coladas', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Strawberry Lemonade', 10000, 'Lemonades', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Strawberry Milkshake', 12000, 'Milkshakes', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Strawberry Mojito', 15000, 'Mojitos', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'The Vegetarian Sandwiches', 20000, 'Sandwiches', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Tiramisu', 14000, 'Desserts', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Traditional Ugandan BreakFast', 25000, 'Breakfast', 'https://i.ibb.co/8w3zFJp/820c5969b860.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Tropical Smoothie', 13000, 'Smoothies', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Ugandan Coffee', 8000, 'Drinks', 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Ugandan Coffee', 8000, 'Drinks', 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Ugandan Simple Breakfast', 15000, 'Breakfast', 'https://i.ibb.co/VY273wrk/f81c736947a1.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Vanilla Latte', 14000, 'Flavoured Lattes', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Vanilla Milkshake', 12000, 'Milkshakes', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Vegetable Burger', 25000, 'Burgers', 'https://i.ibb.co/wF0fh1Wz/c033f559670f.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Vegetable Samosa', 4000, 'Pies & Samosas', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Vegetarian Pizza', 28000, 'Pizzas', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Waffles with Ice Cream', 18000, 'Desserts', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Warm Oriental Beef and Rocket Salad', 25000, 'All Day Dining', 'https://i.ibb.co/KzSGFBCk/83b9dc64e930.jpg', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Wet Cappuccino', 12000, 'Cappuccinos', '', TRUE, FALSE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'White Bread Loaf', 12000, 'Bread Loaves', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Whole Carrot Cake', 75000, 'Whole Cakes', '', FALSE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Whole Cheesecake', 90000, 'Whole Cakes', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Whole Chocolate Cake', 80000, 'Whole Cakes', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Whole Deep Fried Fish', 30000, 'Main Course', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Whole Fried Nile Perch', 45000, 'Mains', 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Whole Fried Nile Perch', 45000, 'Mains', 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, TRUE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Whole Tilapia Grilled', 35000, 'Main Course', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');
INSERT INTO products (id, name, price, category, image, available, requires_kitchen, description, branch_id, branch_name, linked_ingredient_id, deduct_from_inventory, inventory_deduct_amount, add_ons, created_at, updated_at, organization_id)
VALUES (uuid_generate_v4(), 'Whole Wheat Loaf', 15000, 'Bread Loaves', '', TRUE, TRUE, NULL, 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', NULL, FALSE, 1, '[]'::jsonb, NOW(), NOW(), 'a45521c0-d218-4916-be3e-e28ce5b7dffa');

COMMIT;
