-- Migration 011: Migrate MIRABAL CAFE zones from Supabase to Neon
-- 21 zones total, all mapped to org a45521c0... and branch ce9e7783...

INSERT INTO zones (id, name, icon, description, branch_id, branch_name, tables, organization_id, created_at, updated_at)
VALUES
(uuid_generate_v4(), 'B Section', '🍷', 'Bar & Lounge Dining', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","seatsCount":2,"tableNumber":"B1"},{"shape":"round","seatsCount":2,"tableNumber":"B2"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'Deck', '🌿', 'Deck tables', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","status":"available","seatsCount":6,"tableNumber":"D1"},{"shape":"round","seatsCount":6,"tableNumber":"D2"},{"shape":"round","seatsCount":6,"tableNumber":"D3"},{"shape":"round","seatsCount":6,"tableNumber":"D4"},{"shape":"round","seatsCount":6,"tableNumber":"D5"},{"shape":"round","seatsCount":6,"tableNumber":"D6"},{"shape":"round","seatsCount":6,"tableNumber":"D7"},{"shape":"round","seatsCount":6,"tableNumber":"D8"},{"shape":"round","seatsCount":6,"tableNumber":"D9"},{"shape":"round","seatsCount":6,"tableNumber":"D10"},{"shape":"round","seatsCount":6,"tableNumber":"D11"},{"shape":"round","seatsCount":6,"tableNumber":"D12"},{"shape":"round","seatsCount":6,"tableNumber":"D13"},{"shape":"round","seatsCount":4,"tableNumber":"D14"},{"shape":"round","seatsCount":12,"tableNumber":"D15"},{"shape":"round","seatsCount":6,"tableNumber":"D16"},{"shape":"round","seatsCount":6,"tableNumber":"D17"},{"shape":"round","seatsCount":6,"tableNumber":"D18"},{"shape":"round","seatsCount":6,"tableNumber":"D19"},{"shape":"round","seatsCount":6,"tableNumber":"D20"},{"shape":"round","seatsCount":6,"tableNumber":"D21"},{"shape":"round","seatsCount":6,"tableNumber":"D22"},{"shape":"round","seatsCount":6,"tableNumber":"D23"},{"shape":"round","seatsCount":6,"tableNumber":"D24"},{"shape":"round","seatsCount":6,"tableNumber":"D25"},{"shape":"round","seatsCount":6,"tableNumber":"D26"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'E&G Lower Section', '🌿', 'E&G Lower Section Tables', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","status":"occupied","seatsCount":4,"tableNumber":"G1"},{"shape":"round","seatsCount":4,"tableNumber":"G2"},{"shape":"round","seatsCount":4,"tableNumber":"G3"},{"shape":"round","seatsCount":4,"tableNumber":"G4"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'E&G Section', '🌿', 'E&G Section Tables', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","status":"occupied","seatsCount":4,"tableNumber":"E11"},{"shape":"round","seatsCount":4,"tableNumber":"E12"},{"shape":"round","seatsCount":4,"tableNumber":"E13"},{"shape":"round","seatsCount":4,"tableNumber":"E14"},{"shape":"round","seatsCount":4,"tableNumber":"E15"},{"shape":"round","seatsCount":4,"tableNumber":"E16"},{"shape":"round","seatsCount":4,"tableNumber":"E17"},{"shape":"round","seatsCount":4,"tableNumber":"E18"},{"shape":"round","seatsCount":4,"tableNumber":"E19"},{"shape":"round","seatsCount":4,"tableNumber":"E110"},{"shape":"round","seatsCount":4,"tableNumber":"E111"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'Elephant', '🌿', 'Elephant Section', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","seatsCount":2,"tableNumber":"ELE1"},{"shape":"round","seatsCount":6,"tableNumber":"ELE2"},{"shape":"round","seatsCount":2,"tableNumber":"ELE3"},{"shape":"round","seatsCount":2,"tableNumber":"ELE4"},{"shape":"round","seatsCount":2,"tableNumber":"ELE5"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'F&B Lower Section', '🍃', 'Lower Terrace Dining Area', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"rectangle","seatsCount":6,"tableNumber":"L1"},{"shape":"rectangle","seatsCount":6,"tableNumber":"L2"},{"shape":"round","seatsCount":4,"tableNumber":"L3"},{"shape":"round","seatsCount":4,"tableNumber":"L4"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'F&B Section', '🌿', 'Main F&B Dining Area', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","seatsCount":4,"tableNumber":"E1"},{"shape":"round","seatsCount":4,"tableNumber":"E2"},{"shape":"round","seatsCount":4,"tableNumber":"E3"},{"shape":"round","seatsCount":4,"tableNumber":"E4"},{"shape":"round","seatsCount":4,"tableNumber":"E5"},{"shape":"round","seatsCount":4,"tableNumber":"E6"},{"shape":"round","seatsCount":4,"tableNumber":"E7"},{"shape":"round","seatsCount":4,"tableNumber":"E8"},{"shape":"round","seatsCount":4,"tableNumber":"E9"},{"shape":"round","seatsCount":4,"tableNumber":"E10"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'GAZEBO BACK', '🌿', 'GAZEBO BACK SEATS', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","seatsCount":3,"tableNumber":"GAZEBO BACK1"},{"shape":"round","seatsCount":3,"tableNumber":"GAZEBO BACK2"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'GAZEBO FRONT', '🌿', 'GAZEBO FRONT SEATS', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","seatsCount":1,"tableNumber":"GAZEBO FRONT1"},{"shape":"round","seatsCount":1,"tableNumber":"GAZEBO FRONT2"},{"shape":"round","seatsCount":8,"tableNumber":"GAZEBO FRONT3"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'INFRONT', '🌿', 'FRONT SEATS', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","status":"occupied","seatsCount":4,"tableNumber":"FR1"},{"shape":"round","status":"occupied","seatsCount":4,"tableNumber":"FR2"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'Joiner Section', '✨', 'Large Group Tables', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"rectangle","seatsCount":8,"tableNumber":"J1"},{"shape":"rectangle","seatsCount":8,"tableNumber":"J2"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'L-Section', '🌿', 'L-Section Tables', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","status":"occupied","seatsCount":4,"tableNumber":"L-SECTION1"},{"shape":"round","status":"occupied","seatsCount":4,"tableNumber":"L-SECTION2"},{"shape":"round","status":"available","seatsCount":4,"tableNumber":"L-SECTION3"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'LOVERS CORNER', '🌿', 'LOVERS CORNER SEATS', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","seatsCount":3,"tableNumber":"LOVERS CORNER1"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'LOWER SECTION', '🌿', 'LOWER SECTION', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","status":"occupied","seatsCount":4,"tableNumber":"L-P1"},{"shape":"round","seatsCount":4,"tableNumber":"L-P2"},{"shape":"round","seatsCount":4,"tableNumber":"L-P3"},{"shape":"round","seatsCount":4,"tableNumber":"L-P4"},{"shape":"round","seatsCount":4,"tableNumber":"L-P5"},{"shape":"round","seatsCount":4,"tableNumber":"L-P6"},{"shape":"round","seatsCount":4,"tableNumber":"L-P7"},{"shape":"round","seatsCount":4,"tableNumber":"L-P8"},{"shape":"round","seatsCount":4,"tableNumber":"L-P9"},{"shape":"round","seatsCount":4,"tableNumber":"L-P10"},{"shape":"round","seatsCount":4,"tableNumber":"L-P11"},{"shape":"round","seatsCount":4,"tableNumber":"L-P12"},{"shape":"round","seatsCount":4,"tableNumber":"L-P13"},{"shape":"round","seatsCount":4,"tableNumber":"L-P14"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'P Section', '🌿', 'P Section Tables', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","status":"available","seatsCount":4,"tableNumber":"P1"},{"shape":"round","status":"occupied","seatsCount":4,"tableNumber":"P2"},{"shape":"round","status":"occupied","seatsCount":4,"tableNumber":"P3"},{"shape":"round","status":"occupied","seatsCount":4,"tableNumber":"P4"},{"shape":"round","status":"occupied","seatsCount":4,"tableNumber":"P5"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'TERRACE', '🌿', 'TERRACE 1 SEATS', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","seatsCount":2,"tableNumber":"TERRACE 11"},{"shape":"round","seatsCount":2,"tableNumber":"TERRACE 12"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'TERRACE 2', '🌿', 'TERRACE 2 SEATS', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"round","seatsCount":2,"tableNumber":"TERRACE 21"},{"shape":"round","seatsCount":2,"tableNumber":"TERRACE 22"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW()),
(uuid_generate_v4(), 'VIP Lounge', '👑', 'Executive Private Dining', 'ce9e7783-5a93-4dee-b237-aaed8e7ec746', 'MRABAL CAFE', '[{"shape":"rectangle","seatsCount":6,"tableNumber":"VIP-1"}]'::jsonb, 'a45521c0-d218-4916-be3e-e28ce5b7dffa', NOW(), NOW());
