'use client';

import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, Eye, EyeOff, ShieldCheck, WifiOff } from 'lucide-react';
import { activateDevice, createDeviceProof, getDeviceId } from '@/lib/device-auth-client';
import { verifyOfflineCredentials, verifyOfflinePin, storeOfflinePasswordHash, storeOfflinePin, cacheOfflineAuth } from '@/lib/offlineAuth';

type Mode='password'|'pin'|'activate';
function profile(s:any){return {id:s.id,name:s.name||'Staff',email:s.email||'',role:s.role,branch:s.branch||s.branch_name||'Branch',assignedBranchId:s.assigned_branch_id||s.assignedBranchId||null,organizationId:s.organization_id||s.organizationId||null,status:s.status||'active',avatar:s.avatar};}

export function KrownAuthGateV2(){
 const [visible,setVisible]=useState(false),[mode,setMode]=useState<Mode>('password'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[pin,setPin]=useState(''),[activation,setActivation]=useState(''),[showPassword,setShowPassword]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[deviceId,setDeviceId]=useState<string|null>(()=>getDeviceId()),[online,setOnline]=useState(()=>typeof navigator==='undefined'?true:navigator.onLine);
 const activated=!!deviceId;
 const strength=useMemo(()=>{let n=0;if(password.length>=8)n++;if(password.length>=12)n++;if(/[A-Za-z]/.test(password)&&/\d/.test(password))n++;if(/[^A-Za-z0-9]/.test(password))n++;return ['','Weak','Fair','Strong','Very strong'][n];},[password]);
 useEffect(()=>{const sync=()=>setVisible(window.location.pathname==='/'&&!localStorage.getItem('krown_session_token'));const on=()=>setOnline(true),off=()=>setOnline(false);sync();window.addEventListener('storage',sync);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('storage',sync);window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[]);
 function finish(s:any,token:string,d?:string|null){localStorage.setItem('krown_session_token',token);localStorage.setItem('krown_staff_profile',JSON.stringify(profile(s)));if(s.organization_id)localStorage.setItem('krown_organization_id',s.organization_id);if(s.assigned_branch_id)localStorage.setItem('krown_branch_id',s.assigned_branch_id);if(d)localStorage.setItem('krown_device_id',d);sessionStorage.setItem('krown_active_session','true');setVisible(false);window.dispatchEvent(new CustomEvent('krown-authenticated',{detail:{staffId:s.id,organizationId:s.organization_id,branchId:s.assigned_branch_id}}));}
 async function loginPassword(){if(!email.trim()||!password){setError('Enter your email and password.');return;}setBusy(true);setError('');try{
   // First attempt is intentionally device-free. Super Admin and Restaurant Admin are
   // authenticated server-side here and therefore never require device activation.
   let response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email.trim().toLowerCase(),password})});
   let data=await response.json().catch(()=>({}));
   if(response.ok&&data?.data?.staff&&data?.data?.token){await cacheOfflineAuth(profile(data.data.staff));finish(data.data.staff,data.data.token,data.data.deviceId);return;}
   const activationRequired=response.status===403&&/activated|device/i.test(String(data?.error||''));
   if(!activationRequired)throw new Error(data?.error||'Wrong email or password.');
   if(!activated){setMode('activate');throw new Error('This account requires activation of this computer before staff login.');}
   if(!online){const cached=await verifyOfflineCredentials(email,password);if(!cached)throw new Error('Wrong email or password for this activated restaurant or branch.');finish(cached.staff,`offline:${cached.deviceId}:${Date.now()}`,cached.deviceId);return;}
   const proof=await createDeviceProof(deviceId!);response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email.trim().toLowerCase(),password,deviceId,deviceProof:proof})});data=await response.json().catch(()=>({}));if(!response.ok||!data?.data?.staff||!data?.data?.token)throw new Error(data?.error||'Wrong email or password for this restaurant or branch.');await cacheOfflineAuth(profile(data.data.staff));await storeOfflinePasswordHash(email.trim().toLowerCase(),password);finish(data.data.staff,data.data.token,data.data.deviceId);
 }catch(e:any){setError(e?.message||'Unable to sign in.');}finally{setBusy(false)}}
 async function loginPin(){if(!/^\d{4,6}$/.test(pin)){setError('Enter your 4–6 digit PIN.');return;}if(!activated){setMode('activate');setError('Activate this computer before using a staff PIN.');return;}setBusy(true);setError('');try{if(!online){const c=await verifyOfflinePin(pin);if(!c)throw new Error('Wrong PIN for this activated restaurant or branch.');finish(c.staff,`offline:${c.deviceId}:${Date.now()}`,c.deviceId);return;}const proof=await createDeviceProof(deviceId!);const r=await fetch('/api/auth/pin-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin,deviceId,challenge:proof.challenge,signature:proof.signature})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.data?.staff||!d?.data?.token)throw new Error(d?.error||'Wrong PIN.');await cacheOfflineAuth(profile(d.data.staff));await storeOfflinePin(profile(d.data.staff),pin);finish(d.data.staff,d.data.token,d.data.deviceId);}catch(e:any){setError(e?.message||'Unable to sign in.')}finally{setBusy(false)}}
 async function doActivate(){const code=activation.trim().replace(/^KROWN-ACTIVATE:/i,'');if(!/^\d{8}$/.test(code)){setError('Enter the 8-digit activation code.');return;}setBusy(true);setError('');try{const d=await activateDevice(code);localStorage.setItem('krown_device_id',d.id);if(d.organization_id)localStorage.setItem('krown_organization_id',d.organization_id);if(d.branch_id)localStorage.setItem('krown_branch_id',d.branch_id);setDeviceId(d.id);setActivation('');setMode('password');}catch(e:any){setError(e?.message||'Invalid activation code.')}finally{setBusy(false)}}
 if(!visible)return null;
 return <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-[#F4F4F6] dark:bg-[#08080A] p-4"><div className="w-full max-w-md rounded-[2rem] bg-white/95 dark:bg-[#121216]/95 backdrop-blur-2xl border border-black/5 dark:border-white/10 shadow-2xl p-7">
  <div className="text-center mb-7"><div className="w-16 h-16 rounded-2xl bg-white dark:bg-[#1D1D22] p-2 shadow-xl mx-auto mb-4"><img src="https://iili.io/nK49crl.png" alt="KROWN ERP" className="w-full h-full rounded-xl object-contain"/></div><h1 className="text-2xl font-black text-slate-900 dark:text-white">KROWN ERP</h1><p className="text-xs text-slate-500 mt-1">Secure restaurant access</p></div>
  <div className="grid grid-cols-2 gap-1 p-1 rounded-2xl bg-slate-100 dark:bg-black/30 mb-6"><button onClick={()=>{setMode('password');setError('')}} className={`py-3 rounded-xl text-xs font-black ${mode==='password'?'bg-white dark:bg-[#1D1D22] shadow':''}`}>Email + Password</button><button onClick={()=>{setMode('pin');setError('')}} className={`py-3 rounded-xl text-xs font-black ${mode==='pin'?'bg-white dark:bg-[#1D1D22] shadow':''}`}>PIN</button></div>
  {error&&<div className="mb-5 p-3.5 bg-red-500/10 border border-red-500/20 rounded-2xl flex gap-2 text-red-500 text-xs font-semibold"><AlertCircle className="w-4 h-4 shrink-0"/>{error}</div>}
  {mode==='password'&&<div className="space-y-4"><input autoFocus value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email address" className="w-full rounded-2xl bg-slate-50 dark:bg-black/30 border border-black/5 dark:border-white/10 px-4 py-4 text-sm outline-none focus:ring-2 focus:ring-orange-500/40"/><div className="relative"><input value={password} onChange={e=>setPassword(e.target.value)} type={showPassword?'text':'password'} placeholder="Password" onKeyDown={e=>e.key==='Enter'&&loginPassword()} className="w-full rounded-2xl bg-slate-50 dark:bg-black/30 border border-black/5 dark:border-white/10 px-4 py-4 pr-12 text-sm outline-none focus:ring-2 focus:ring-orange-500/40"/><button type="button" onClick={()=>setShowPassword(v=>!v)} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400">{showPassword?<EyeOff className="w-5 h-5"/>:<Eye className="w-5 h-5"/>}</button></div>{password&&<p className="text-[11px] text-slate-500">Password strength: <b>{strength}</b></p>}<button disabled={busy} onClick={loginPassword} className="w-full py-4 rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 text-white font-black">{busy?'Verifying…':'Sign in'}</button><div className="text-center text-[11px] text-slate-400">{activated?<span className="inline-flex items-center gap-1"><ShieldCheck className="w-3.5 h-3.5 text-emerald-500"/>Computer activated</span>:<span>This account may require computer activation.</span>}{!online&&<span className="ml-2 inline-flex items-center gap-1"><WifiOff className="w-3 h-3"/>Offline</span>}</div></div>}
  {mode==='pin'&&<div className="space-y-5"><div className="text-center"><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-emerald-500/10 text-emerald-600 text-[10px] font-black uppercase"><ShieldCheck className="w-3.5 h-3.5"/> {activated?'Activated device':'Activation required'}</div></div><input autoFocus type="password" inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} onKeyDown={e=>e.key==='Enter'&&loginPin()} placeholder="••••" className="w-full text-center tracking-[.45em] text-3xl font-black bg-slate-50 dark:bg-black/30 border rounded-2xl py-5"/><button disabled={busy||!activated} onClick={loginPin} className="w-full py-4 rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 text-white font-black">{busy?'Verifying…':'Unlock with PIN'}</button>{!activated&&<button onClick={()=>setMode('activate')} className="w-full py-3 rounded-2xl bg-slate-100 dark:bg-white/5 font-bold text-sm">Activate this computer</button>}</div>}
  {mode==='activate'&&<div className="space-y-4"><h2 className="text-xl font-black text-center text-slate-900 dark:text-white">Activate this computer</h2><p className="text-sm text-center text-slate-500">Use the activation code supplied by the restaurant administrator.</p><input autoFocus inputMode="numeric" maxLength={8} value={activation} onChange={e=>setActivation(e.target.value.replace(/\D/g,''))} onKeyDown={e=>e.key==='Enter'&&doActivate()} placeholder="8-digit code" className="w-full text-center tracking-[.3em] text-2xl font-black bg-slate-50 dark:bg-black/30 border rounded-2xl py-5"/><button disabled={busy} onClick={doActivate} className="w-full py-4 rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 text-white font-black">{busy?'Activating…':'Activate'}</button><button onClick={()=>setMode('password')} className="w-full py-3 text-xs font-bold text-slate-500">Back to sign in</button></div>}
 </div></div>;
}
